---
- name: Add ASDF to Manage multiple runtime versions https://asdf-vm.com/
  tags:
    - asdf

  block:
    - name: Download asdf
      become: false
      git:
        repo: https://github.com/asdf-vm/asdf.git
        version: v0.10.0
        dest: '{{ home }}/.asdf'
        depth: 1
      tags:
        - dotfiles

    - name: Install asdf
      lineinfile:
        path: '{{ home }}/.config/fish/config.fish'
        search_string: asdf.fish
        line: source "$HOME/.asdf/asdf.fish"

    - name: Create fish completion directory
      file:
        path: '{{ home }}/.config/fish/completions'
        mode: u=rwx,g=rx,o=rx

    - name: Create a symbolic link
      ansible.builtin.file:
        src: '{{ home }}/.asdf/completions/asdf.fish'
        dest: '{{ home }}/.config/fish/completions/asdf.fish'
        state: link

    # ASDF python
    - name: check for asdf python Plugin
      stat:
        path: '{{ home }}/.asdf/plugins/python'
      register: asdf_python_plugin

    - name: Install asdf Plugin for nodejs
      command: asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git
      args:
        executable: /usr/bin/fish
      when: not asdf_python_plugin.stat.exists

    # ASDF nodejs
    - name: check for asdf nodejs Plugin
      stat:
        path: '{{ home }}/.asdf/plugins/nodejs'
      register: asdf_nodejs_plugin

    - name: Install asdf Plugin for nodejs
      command: asdf plugin add nodejs
      args:
        executable: /usr/bin/fish
      when: not asdf_nodejs_plugin.stat.exists
