---
- name: Terminal tasks
  tags:
    - terminal
    - essential

  block:
    - name: Ranger File Manager tasks
      include_tasks: ranger.yml
      tags:
        - ranger

    - name: asdf tasks
      include_tasks: asdf.yml
      tags:
        - ranger

    - name: Install Monitoring tools
      become: true
      apt:
        name:
          - htop
        state: present
      tags:
        - monitoring

    - name: Install Bat
      become: true
      apt:
        name:
          - bat
        state: present
      tags:
        - bat

    - name: Syntax Highlighting for Less pager
      become: true
      apt:
        name:
          - libsource-highlight-common
          - source-highlight
        state: present
      tags:
        - less

    - name: Install decors/fish-source-highlight
      shell: fisher install decors/fish-source-highlight
      when: true
      args:
        executable: /usr/bin/fish
      tags:
        - less
        - plugins

    - name: Install Fdfind
      become: true
      apt:
        name:
          - fd-find
        state: present
      tags:
        - find

    - name: Install just (command runner) https://github.com/casey/just
      snap:
        name: just
        state: present
        channel: edge
        classic: true
      tags:
        - just

    - name: Install direnv
      become: true
      apt:
        name:
          - direnv
        state: present
      tags:
        - direnv
