---
- hosts: localhost
  become: yes

  tasks:
    - name: Install Monitoring tools
      apt:
        name:
          - htop
        state: present
      tags:
        - terminal
        - essential
        - monitoring
