---
- name: Terminal tasks
  tags:
    - terminal
    - essential

  block:
    - name: Install terminal
      become: true
      apt:
        name:
          - guake
        state: present
    
    - name: Syntax Highlighting for Less pager tasks
      include_tasks: highlight.yml
      tags:
        - highlight
        - less

    - name: Ranger File Manager tasks
      include_tasks: ranger.yml
      tags:
        - ranger

    - name: asdf tasks
      include_tasks: asdf.yml
      tags:
        - asdf

    - name: Install Monitoring tools
      become: true
      apt:
        name:
          - htop
        state: present
      tags:
        - monitoring

    - name: Install Bat
      become: true
      apt:
        name:
          - bat
        state: present
      tags:
        - bat

    - name: Install Fdfind
      become: true
      apt:
        name:
          - fd-find
        state: present
      tags:
        - find

    - name: Install just (command runner) https://github.com/casey/just
      snap:
        name: just
        state: present
        channel: edge
        classic: true
      tags:
        - just

    - name: Add `just` completions to Fish
      become: false
      shell: just --completions fish > $HOME/.config/fish/completions/just.fish
      when: true
      tags:
        - just


    - name: Install direnv
      become: true
      apt:
        name:
          - direnv
        state: present
      tags:
        - direnv

    - name: Install ripgrep
      become: true
      apt:
        name:
          - ripgrep
        state: present
      tags:
        - ripgrep
        - find

    - name: Install eza (exa replacement)
      become: true
      apt:
        name:
          - eza
        state: present
      tags:
        - exa
        - find
