---
- name: Ranger tasks
  tags:
    - ranger

  block:
    - name: Install Ranger Terminal File Manager
      become: true
      apt:
        name:
          - ranger
      # when package is outdated compared to pypi
      # become: false
      # pip:
      #   name: ranger-fm
      #   extra_args: --user

    - name: Generate Ranger config
      ansible.builtin.command: 
        argv:
          - ranger
          # - '{{ home }}/.local/bin/ranger'
          - --copy-config=scope
        creates: ~/.config/ranger/scope.sh
