---
- hosts: localhost
  name: Provision a machine with basics
  become: true

  vars_files:
    - .secret.yml

  roles:
    - role: deploy_ssh_keys
      tags: ssh
    - role: ./roles/configure_aws
      tags: aws
    - role: ./roles/configure_browser
      tags: browser
    - role: ./roles/configure_code_ide
      tags: ide
    - role: ./roles/configure_container
      tags: container
    - role: ./roles/configure_dotfiles
      tags: dotfiles
    - role: ./roles/configure_desktop
      tags: desktop
    - role: ./roles/configure_git
      tags: git
    - role: ./roles/configure_infra_management
      tags: infra-management
    - role: ./roles/configure_nodejs
      tags: nodejs
    - role: ./roles/configure_offline
      tags: offline
    - role: ./roles/configure_python
      tags: python
    - role: ./roles/configure_requirements
      tags: requirements
    - role: ./roles/configure_security
      tags: security
    - role: ./roles/configure_shells
      tags: shells
    - role: ./roles/configure_terminal
      tags: terminal
    - role: ./roles/configure_tmux
      tags: tmux
    - role: ./roles/manage_machine
      tags: machine
