---
- name: Remove useless packages from the cache
  apt:
    autoclean: yes
  listen: apt-autoclean
  tags: apt

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
  listen: apt-autoremove
  tags: apt
