---
- name: Browser tasks
  tags:
    - browser

  block:
    - name: Install Firefox
      include_tasks: firefox.yml
      tags:
        - firefox

    - name: Install Brave Browser
      include_tasks: brave.yml
      tags:
        - brave