---
- name: docker tasks
  tags:
    - docker
    - container

  block:
    - name: Install Docker requirements
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release

    - name: Add Docker’s official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      tags:
        - repo

    - name: Add Docker repository
      apt_repository:
        repo: 'deb https://download.docker.com/linux/ubuntu {{ distro_codename }} stable'
        state: present
        update_cache: true
      tags:
        - repo

    - name: Install Docker packages 
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io

    - name: Install linter (hadolint)
      get_url:
        url: https://github.com/hadolint/hadolint/releases/download/v2.10.0/hadolint-Linux-x86_64
        dest: /usr/local/bin/hadolint
        mode: '+x'
      tags:
        - linter

    - name: Install Docker test with dgoss
      get_url:
        url: https://raw.githubusercontent.com/aelsabbahy/goss/master/extras/dgoss/dgoss
        dest: /usr/local/bin/dgoss
        mode: '+rx'
      tags:
        - test

    - name: Install goss
      get_url:
        url: https://github.com/aelsabbahy/goss/releases/download/{{ goss_version }}/goss-linux-amd64
        dest: /usr/local/bin/goss
        mode: '+rx'
      tags:
        - test
