---
- hosts: localhost
  become: true

  vars:
    distro_name: 'Ubuntu'
    distro_version: '20.04'

  tasks:
    - name: Install the gpg key for Buildah
      apt_key:
        url: 'https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/x{{ distro_name }}_{{ distro_version }}/Release.key'
        state: present
      tags:
        - container

    - name: Add Buildah PPA source to repositories list
      apt_repository:
        repo: 'deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/x{{ distro_name }}_{{ distro_version }}/ /'
        state: present
        update_cache: true
      tags:
        - container

    - name: Install the Docker tooling alternatives
      apt:
        name:
          - buildah
          - skopeo
          - podman
        state: latest
      tags:
        - container

    - name: Install Compose Switch
      get_url:
        url: https://github.com/docker/compose-switch/releases/download/v1.0.4/docker-compose-linux-amd64
        dest: /usr/local/bin/compose-switch
        mode: '+x'
      tags:
        - container
        - compose

    - name: Define an alternatives group for the docker-compose command
      shell: >
        update-alternatives \
          --install \
            /usr/local/bin/docker-compose \
            docker-compose \
            /usr/local/bin/compose-switch \
            99
      tags:
        - container
        - compose

    - name: Install linter (hadolint)
      get_url:
        url: https://github.com/hadolint/hadolint/releases/download/v2.10.0/hadolint-Linux-x86_64
        dest: /usr/local/bin/hadolint
        mode: '+x'
      tags:
        - container
        - linter
