---

- name: Docker playbook
  include_tasks: docker.yml
  tags:
    - container
    - docker

- name: Docker compose playbook
  include_tasks: docker-compose.yml
  tags:
    - container
    - compose

- name: Podman playbook
  include_tasks: podman.yml
  tags:
    - container
    - podman


