---

- name: Docker playbook
  include_tasks: docker.yml
  tags:
    - container
    - docker

- name: Docker compose playbook
  include_tasks: docker-compose.yml
  tags:
    - container
    - compose

- name: Podman playbook
  include_tasks: podman.yml
  tags:
    - container
    - podman

- name: Install DevContainer cli
  become: false
  yarn:
    name: '@devcontainers/cli'
    global: true
    state: present
  tags:
    - container
    - devcontainers