---
- name: Install Tmux
  apt:
    name:
      - tmux
    state: present
  tags:
    - terminal
    - essential

- name: Install requirements
  apt:
    name:
      # - xcopy # doesn't exist anymore?
      - xclip
    state: present
  tags:
    - tmux
    - terminal

- name: Remove Default Tmux Configuration Directory
  ansible.builtin.file:
    path: '{{ home }}/.tmux'
    state: absent

- name: Checkout Personal Tmux Configuration From Github
  become: false
  git:
    repo: git@github.com:edouard-lopez/tmux-config.git
    dest: '{{ home }}/.tmux'
    depth: 1
  tags:
    - tmux
    - configuration
