---
- name: Fingerprint authentication tasks
  tags:
    - fingerprint

  block:
    # https://github.com/3v1n0/libfprint/blob/c6f5f0ee5f4d5341df7976c43b48ca748f4b71fa/README.md
    - name: Install fingerprint fixing tools for (138a:0097)
      snap:
        - validity-sensors-tools
    
    - name: Give it access to the usb devices
      command: |
        snap connect validity-sensors-tools:raw-usb \
        && snap connect validity-sensors-tools:hardware-observe

    - name: Initialize the device
      command: validity-sensors-tools.initializer

    - name: Test the device
      command: validity-sensors-tools.led-test

    - name: This is needed and only works in 138a:0097
      command: validity-sensors-tools.enroll --finger-id 0

    # - name: See other available tools
    #   command: validity-sensors-tools --help

    - name: Install fingerprint tools
      apt:
        name:
          - libpam-fprintd
          - fprintd
 
    - name: Force hardware update
      command: fwupdmgr refresh --force && fwupdmgr get-updates

    - name: update PAM configuration
      command: pam-auth-update
