---
- name: Instal Delta A syntax-highlighting pager for git, diff, and grep output
  tags:
    - ide
    - vim

  block:
    - name: Install Vim
      apt:
        name:
          - vim
        state: present

    - name: Install Vim-plug (Plugin Manager)
      get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: '{{ home }}/.vim/autoload/plug.vim'
        mode: +x
        force: true
      tags:
        - plugins
      notify:
        - install-vim-plugins
        - vim-configure-base16-theme
      changed_when: true
