galaxy_info:
  author: Édouard Lopez
  description: Manage machine (e.g. updates, etc.)
  license: MIT
  min_ansible_version: 2.1
  platforms:
    - name: Ubuntu
      versions:
        - all
  galaxy_tags: []
dependencies: []
