---
- hosts: localhost
  become: true

  vars:
    home: "{{ lookup('env', 'HOME') }}"

  tasks:
    - name: Checkout Dotfiles From Github
      become: false
      git:
        repo: git@github.com:edouard-lopez/dotfiles.git
        dest: '{{ HOME }}/dotfiles'
        depth: 1
      tags:
        - dotfiles

    - name: Copy *rc Files
      copy:
        src: '{{ item }}'
        dest: '{{ HOME }}/'
        backup: yes
      with_fileglob:
        - '{{ HOME }}/dotfiles/*rc'
      tags:
        - configuration
        - shell

    - name: Set Configuration for Fish
      copy:
        src: '{{ HOME }}/dotfiles/config.fish'
        dest: '{{ HOME }}/.config/fish/config.fish'
        backup: yes

      tags:
        - fish
        - shell
