---
- name: Instal Delta A syntax-highlighting pager for git, diff, and grep output
  tags:
    - git
    - delta

  block:
    - name: Install Delta from repository
      apt:
        deb: https://github.com/dandavison/delta/releases/download/0.13.0/git-delta_0.13.0_amd64.deb

    - name: Add config for Preview in Terminal Tool
      blockinfile:
        path: '{{ home }}/.gitconfig'
        backup: true
        marker: '# {mark} Added by ansbible `delta` task'
        content: |
          [core]
              pager = delta

          [interactive]
              diffFilter = delta --color-only --features=interactive
              
          [delta]
              features = decorations
              navigate = true
              side-by-side = true

          [delta "interactive"]
              keep-plus-minus-markers = false

          [delta "decorations"]
              commit-decoration-style = blue ol
              commit-style = raw
              file-style = omit
              # hunk-header-decoration-style = blue box
              # hunk-header-file-style = red
              # hunk-header-line-number-style = "#067a00"
              # hunk-header-style = file line-number syntax
