---
- hosts: localhost
  become: true

  tasks:
    - name: Install git, git-gui and gitk
      apt:
        name:
          - git
          - git-gui
          - gitk
        state: latest
      tags:
        - git

    - name: Install Gitlab CLI
      community.general.snap:
        name: glab
        state: present
        channel: latest/edge
      tags:
        - gitlab
    - name: Grant SSH access to Gitlab CLI
      shell: snap connect glab:ssh-keys
      tags:
        - gitlab
