---
- name: Install git, git-gui and gitk
  apt:
    name:
      - git
      - git-gui
      - gitk
    state: present
  tags:
    - git

- name: Instal GitLab related tool
  include_tasks: gitlab.yml
  tags:
    - git
    - gitlab
    - glab-cli

- name: 'Github CLI: Install the gpg key'
  apt_key:
    url: 'https://cli.github.com/packages/githubcli-archive-keyring.gpg'
    keyring: /usr/share/keyrings/githubcli-archive-keyring.gpg
    state: present
  tags:
    - github-cli
    
- name: 'Github CLI: Add source to repositories list'
  apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg arch=amd64] https://cli.github.com/packages stable main
    state: present
    update_cache: true
  tags:
    - github-cli

- name: Install the gh
  apt:
    name: gh
    state: present
  tags:
    - github-cli

- name: Instal Delta A syntax-highlighting pager for git, diff, and grep output
  include_tasks: delta.yml
  tags:
    - git
    - delta
