galaxy_info:
  author: Édouard Lopez
  description: configure requirements
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - all
  galaxy_tags: []
dependencies: []
