---
- name: Set up multiple SSH authorized keys
  ansible.posix.authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "{{ lookup('file', item) }}"
  with_fileglob:
    - "../public_keys/*.pub"
  tags: ssh
