---
- name: Desktop tasks
  tags:
    - desktop

  block:
    - name: Install Shutter (screenshot)
      apt:
        name:
          - shutter
        state: present
      tags:
        - shutter

    - name: Install ibus
      apt:
        name:
          - ibus
          - diodon
        state: present

    - name: ulauncher tasks
      include_tasks: ulauncher.yml
      tags:
        - ulauncher

    - name: signal tasks
      include_tasks: signal.yml
      tags:
        - signal