---
- hosts: localhost
  become: true

  tags:
    - k8s
    - infra

  tasks:
    - name: Install k9s
      community.general.snap:
        name: k9s
        state: present
      tags:
        - k9s
