---
- name: Install Python 3
  apt:
    name:
      - python3
    state: present
  tags:
    - python
    - essential

- name: Ubuntu Requirements For Installing Pip
  apt:
    name:
      - python3-pip
  tags:
    - python
    - dev

- name: Install development modules
  become: false
  pip:
    name:
      - pipenv
      - pipx
    extra_args: --user
  tags:
    - python
    - dev

- name: Post-install to ensure $PATH is correctly configured
  community.general.pipx:
    name: ensurepath
  when: true
  tags:
    - python
    - dev

- name: Download Poetry
  get_url:
    url: https://install.python-poetry.org
    dest: /tmp/poetry-installer
    mode: 755

- name: Install Poetry
  script: /tmp/poetry-installer
  when: true
