---
- name: "PDM: modern Python package and dependency manager"
  tags:
    - pdm

  block:
    - name: Download PDM
      get_url:
        url: https://raw.githubusercontent.com/pdm-project/pdm/main/install-pdm.py
        dest: /tmp/pdm.py
        mode: 'u+x'
        owner: '{{ user }}'
        group: '{{ user }}'

    - name: Install PDM
      command: python /tmp/pdm.py
      when: true

    - name: Add `PDM` completions to Fish
      become: false
      shell: >
        pdm completion fish > ~/.config/fish/completions/pdm.fish
      args:
        executable: /usr/bin/fish
